spring:
  application:
    name: Multi-Tenant-Booking-System2.0
  datasource:
    url: jdbc:mysql://localhost:3306/BookingSystem
    user: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
  cloudinary:
    cloud-name: ${CLOUDINARY_CLOUD_NAME}
    api-key: ${CLOUDINARY_API_KEY}
    api-secret: ${CLOUDINARY_API_SECRET}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  Subscription:
    amount: 500
  jwt:
    secret: ${JWT_SECRET}
    expiration: 846000
  Mpesa:
    consumer-key: ${MPESA_CONSUMER_KEY}
    consumer-secret: ${MPESA_CONSUMER_SECRET}
    short-code: ${MPESA_SHORT_CODE}
    passkey: ${MPESA_PASSKEY}
    callback-url: ${MPESA_CALLBACK_URL}


